# This is a config for E2B sandbox template.
# You can use template ID (dbe6pq4es6hqj31ybd38) or template name (threatweaver-security) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("threatweaver-security") # Sync sandbox
# sandbox = await AsyncSandbox.create("threatweaver-security") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('threatweaver-security')

team_id = "c95e0b17-985d-4f1c-88ef-858e33bf5b8b"
dockerfile = "Dockerfile"
template_name = "threatweaver-security"
template_id = "dbe6pq4es6hqj31ybd38"
